#!/bin/bash
echo "🚀 DEPLOYING OKX PRICE FIX TO PRODUCTION VPS"
echo "============================================="
echo "Fix: Updated OKX fallback from $45k to real market prices"
echo ""

echo "📋 Files to deploy:"
echo "- core/okx_fetcher.py (UPDATED with real price fallback)"
echo ""

echo "🔄 Step 1: Git Push (Manual - run these commands):"
echo "git add core/okx_fetcher.py"
echo "git commit -m 'Fix OKX fallback prices: $45k → $111k real market data'"
echo "git push origin main"
echo ""

echo "🔄 Step 2: VPS Deploy (Manual - SSH ke VPS):"
echo "ssh root@guardiansofthetoken.id"
echo "cd /root/crypto-analysis-dashboard"
echo "git pull origin main"
echo "docker-compose -f docker-compose-vps.yml down"
echo "docker-compose -f docker-compose-vps.yml up -d --build"
echo ""

echo "🧪 Step 3: Test Production (after deploy):"
echo "curl https://guardiansofthetoken.id/api/signal/top"
echo ""

echo "✅ Expected Result:"
echo "Trading signals should now use current BTC price (~$111,796) instead of $45,000"
echo ""

echo "📊 What the fix does:"
echo "1. Try OKX ticker API for real current price"
echo "2. If ticker fails, use $111,000 estimate (not $45,000)" 
echo "3. Track status: 'fallback_with_real_price' vs 'fallback_estimated'"
echo ""

echo "🎯 Manual Deployment Commands:"
echo "==============================="
echo ""
echo "# On Local (Replit):"
echo "git add core/okx_fetcher.py"
echo "git commit -m '🔧 Fix OKX fallback: $45k → $111k real market data'"
echo "git push origin main"
echo ""
echo "# On VPS:"
echo "ssh root@guardiansofthetoken.id"
echo "cd /root/crypto-analysis-dashboard"
echo "git pull origin main"
echo "docker-compose -f docker-compose-vps.yml restart"
echo ""
echo "✅ Done! Platform akan gunakan real market prices."